### ISSUE TITLE
Can I get .ipa file for the ios-uicatalog application

### ISSUE THREAD

**Issue by Sourabh25** [appium/ios-uicatalog#17]
I have worked with this uicatalog application and on my local i was able to test with .app file itself.
However to test it in a sauce-lab, i need a .ipa format of this app. Could you please provide me that. I could not create it from the xcode project because it seems i don't have apple's developer access.

Thanks

**Comment by KazuCocoa** [comment]
Apple's signature is necessary to build `.ipa` file.
For example, https://needone.app/export-ipa-file-from-xcode-and-install-on-your-mobile/ is the step to get the format
